version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    container_name: todo-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: todo_db_root
      JWT_SECRET: 784d70700f1d6e054a22d042f18abadde02b147e417abf182ae9a842b74981aa
      JWT_EXPIRES_IN: 1d
      ADMIN_TOKEN: supersecret
      APP_MODE: development

volumes:
  mysql_data: